Cisdp 1046 Survey V0, V1 and union
ONS-SST/cis_households pull request #114
Opened 2021-10-28 13:02 UTC by slamothe99

## Pre-review checklist

I have ensured that:

- [ ] Code runs successfully in the development environment.
- [ ] New code is tested to prove that it works. If not, justify reasoning.
- [ ] New code is documented using [type hinting](https://realpython.com/lessons/type-hinting/) and following the [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) docstring format.
- [ ] New code follows the project naming standards.

## Overview of changes

## Post-review checklist

As I merge these changes, I have:

- [ ] Updated the related Jira ticket, including approximate time spent (including review).
- [ ] Moved the related Jira ticket to Done.

2021-11-01 09:51 UTC, slamothe99 commented on cishouseholds/merge.py
> +    return merged_df.union(df3)
test this function with already read in dataframes for v0,1,2

2021-11-02 13:58 UTC, foster999 commented on cishouseholds/extract.py
> +            f"Header of {csv_file_path} ({text_file.first()}) does not match expected header: {expected_raw_header_row}"
This is really useful, thanks for adding it

2021-11-02 14:04 UTC, foster999 requested changes
Please update the test to run with a DataFrame, rather than file on HDFS

2021-11-02 14:04 UTC, foster999 commented on tests/merge/test_merge_survey_tables.py
> +    if test_hadoop:
As discussed, the code should be refactored to use a DataFrame rather than a path to hdfs. This will accommodate a reproducible test

2021-11-02 14:04 UTC, foster999 commented on cishouseholds/pipeline/survey_responses_version_2_ETL.py
> +    # df = placeholder_for_derivation_number_7git-2(df, "month")
Looks like a typo from `git` on the terminal. Not functional though

2021-11-02 16:19 UTC, foster999 commented on cishouseholds/merge.py
> +def merge_survey_tables(tables: List[Union[str, DataFrame]]):
A user could pass more or less than 3 DFs here, so would be safer to have three explicit arguments here

2021-11-03 09:35 UTC, foster999 commented on tests/merge/test_merge_survey_tables.py
> +    output_df = merge_survey_tables([input_df0, input_df1, input_df2])
Think dropping the list square brackets should fix the test here:
```suggestion
    output_df = merge_survey_tables(input_df0, input_df1, input_df2)
```

2021-11-03 09:47 UTC, foster999 commented on tests/merge/test_merge_survey_tables.py
> +    assert_df_equality(expected_df, output_df)
```suggestion
    assert_df_equality(expected_df, output_df, ignore_row_order=True, ignore_column_order=True)
```

2021-11-03 14:02 UTC, foster999 approved these changes

2021-11-03 14:02 UTC, merged