CISDP-994/5 Been_*_last_2_weeks
ONS-SST/cis_households pull request #117
Opened 2021-10-29 13:59 UTC by slamothe99

## Pre-review checklist

I have ensured that:

- [ ] Code runs successfully in the development environment.
- [ ] New code is tested to prove that it works. If not, justify reasoning.
- [ ] New code is documented using [type hinting](https://realpython.com/lessons/type-hinting/) and following the [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) docstring format.
- [ ] New code follows the project naming standards.

## Overview of changes

## Post-review checklist

As I merge these changes, I have:

- [ ] Updated the related Jira ticket, including approximate time spent (including review).
- [ ] Moved the related Jira ticket to Done.

2021-11-01 11:25 UTC, ohibo requested changes
Other than docstrings it looks good to me.

2021-11-01 11:25 UTC, ohibo commented on cishouseholds/derive.py
> +):
Theres no numpy docstrings

2021-11-02 13:57 UTC, foster999 approved these changes

2021-11-02 16:10 UTC, ohibo approved these changes

2021-11-02 16:44 UTC, merged