Cisdp 1040
ONS-SST/cis_households pull request #149
Opened 2021-11-17 13:35 UTC by slamothe99

## Pre-review checklist

I have ensured that:

- [ ] Code runs successfully in the development environment.
- [ ] New code is tested to prove that it works. If not, justify reasoning.
- [ ] New code is documented using [type hinting](https://realpython.com/lessons/type-hinting/) and following the [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) docstring format.
- [ ] New code follows the project naming standards.

## Overview of changes

## Post-review checklist

As I merge these changes, I have:

- [ ] Updated the related Jira ticket, including approximate time spent (including review).
- [ ] Moved the related Jira ticket to Done.

2021-11-17 15:30 UTC, slamothe99 commented on cishouseholds/pipeline/unassayed_blood_ETL.py
> +def blood_delta_ETL(**kwargs):
unassayed_bloods_ETL --change name

2021-11-17 15:30 UTC, slamothe99 commented on cishouseholds/pipeline/timestamp_map.py
> +unprocessed_blood_datetime_map = {""}
remove this

2021-11-17 15:32 UTC, foster999 commented on cishouseholds/pipeline/unassayed_blood_ETL.py
> +    # df = assign_test_target(df, "antibody_test_target", "unassayed_blood_source_file")
Delete unused calls

2021-11-17 15:32 UTC, foster999 commented on cishouseholds/pipeline/timestamp_map.py
> +unprocessed_blood_datetime_map = {""}
Delete this dict if unused

2021-11-22 09:32 UTC, foster999 requested changes

2021-11-22 09:32 UTC, foster999 commented on cishouseholds/pipeline/unassayed_blood_ETL.py
> +        update_table_and_log_source_files(df, "unassayed_blood_test_data", "unassayed_blood_source_file")
Please could "test" be removed from the table name:
```suggestion
        update_table_and_log_source_files(df, "unassayed_blood_sample_data", "unassayed_blood_source_file")
```

2021-11-22 09:35 UTC, foster999 approved these changes
Review changes actioned

2021-11-22 16:24 UTC, merged