1831/22 updated report stage
ONS-SST/cis_households pull request #306
Opened 2022-02-22 11:58 UTC by slamothe99

## Pre-review checklist

I have ensured that:

- [ ] Code runs successfully in the development environment.
- [ ] New code is tested to prove that it works. If not, justify reasoning.
- [ ] New code is documented using [type hinting](https://realpython.com/lessons/type-hinting/) and following the [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) docstring format.
- [ ] New code follows the project naming standards.

## Overview of changes

## Post-review checklist

As I merge these changes, I have:

- [ ] Updated the related Jira ticket, including approximate time spent (including review).
- [ ] Moved the related Jira ticket to Done.

2022-02-22 18:24 UTC, foster999 commented on cishouseholds/pipeline/generate_outputs.py
> +    else:
This isn't needed because line 45/46 above sets the default

2022-02-22 18:25 UTC, foster999 commented on cishouseholds/pipeline/validation_ETL.py
> +    vaccine_columns = []
Part of a different ticket. Please create new branches from origin/main

2022-02-22 18:27 UTC, foster999 commented on cishouseholds/pipeline/generate_outputs.py
> +    window = Window.partitionBy("run_id")
This is a good addition, only selecting the latest run

2022-02-22 18:27 UTC, foster999 requested changes
Some changes suggested in comments, but looks good otherwise

2022-02-23 10:43 UTC, slamothe99 commented on cishouseholds/pipeline/validation_ETL.py
> +                "condition": F.col("work_main_job_changed") != "Yes",
this needs to be inversed such that if yes the columns are filled

2022-02-25 15:31 UTC, foster999 approved these changes

2022-02-25 15:31 UTC, merged