1919 - moved filter response records to validation
ONS-SST/cis_households pull request #334
Opened 2022-03-04 09:19 UTC by slamothe99

## Pre-review checklist

I have ensured that:

- [ ] Code runs successfully in the development environment.
- [ ] New code is tested to prove that it works. If not, justify reasoning.
- [ ] New code is documented using [type hinting](https://realpython.com/lessons/type-hinting/) and following the [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) docstring format.
- [ ] New code follows the project naming standards.

## Overview of changes

## Post-review checklist

As I merge these changes, I have:

- [ ] Updated the related Jira ticket, including approximate time spent (including review).
- [ ] Moved the related Jira ticket to Done.

2022-03-04 10:19 UTC, foster999 approved these changes

2022-03-04 10:21 UTC, foster999 requested changes
Please update the filtering to include the error from this check

2022-03-08 12:02 UTC, ohibo approved these changes

2022-03-08 12:42 UTC, foster999 commented on cishouseholds/validate_class.py
> +                "error_message": "file date should be after visit date",
We're checking the visit date in particular, so reverse wording focus to this. Also describe the rest of the check.

Please substitute in the actual column names using `{}`

```suggestion
                "error_message": "visit date should be before file date when samples have been collected",
```

2022-03-08 13:59 UTC, foster999 commented on cishouseholds/pipeline/validation_ETL.py
> +            "the date in visit_datetime should be before the date expressed in survey_response_source_file and both swab_sample_barcode_column and blood_sample_barcode_column should be null",  # noqa
```suggestion
            "the date in visit_datetime should be before the date expressed in survey_response_source_file when both swab_sample_barcode_column and blood_sample_barcode_column are null",  # noqa:E501
```

2022-03-08 14:00 UTC, foster999 commented on cishouseholds/validate_class.py
> +                "error_message": "the date in {} should be before the date expressed in {} and both {} and {} should be null",  # noqa:E501
```suggestion
                "error_message": "the date in {} should be before the date expressed in {} when both {} and {} are null",  # noqa:E501
```

2022-03-08 14:01 UTC, foster999 approved these changes

2022-03-08 14:10 UTC, merged