2893 - add new brants bridge stage
ONS-SST/cis_households pull request #902
Opened 2023-01-25 15:38 UTC by slamothe99

## Pre-review checklist

I have ensured that:

- [ ] Code runs successfully in the development environment.
- [ ] New code is tested to prove that it meets the specificaiton. If not, justify reasoning.
- [ ] New code is documented using [type hinting](https://realpython.com/lessons/type-hinting/) and following the [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) docstring format.
- [ ] New code follows the project naming standards.

## Overview of changes

2023-01-26 14:46 UTC, izpickle requested changes
Remove references to antibody in name map to avoid confusion with bloods schema. Instead use 'swab'
Think the id_column should probably be the barcode column (which is 'Sample Name' in the csv).  And as such  it might also be easier in the brants_bridge_variable_name_map to have Sample Name: swab_barcode as that will be our joining col and primary key.

2023-01-30 14:30 UTC, slamothe99 commented on cishouseholds/pipeline/mapping.py
> +        "Well": "antibody_test_well_id",
swab_test_well_id

2023-01-30 14:30 UTC, slamothe99 commented on cishouseholds/pipeline/mapping.py
> +        "Sample Name": "sample_name",
swab_sample_barcode

2023-01-31 16:56 UTC, izpickle approved these changes

2023-01-31 16:56 UTC, merged